apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
spec:
  type: filebeat
  version: 8.12.2
  elasticsearchRef:
    name: es-cluster
  kibanaRef:
    name: kibana
  config:
    filebeat.inputs:
    - type: container
      paths:
      - /var/log/containers/*.log
    - type: journald
      id: kubelet
      include_matches:
        - _SYSTEMD_UNIT=kubelet.service

    filebeat.modules:
    - module: traefik
      access:
        enabled: true
        var.paths: ["/var/log/containers/traefik-*.log"]
    parsers:
    - multiline:
      type: pattern
      pattern: '^[[:space:]]+(at|\.{3})[[:space:]]+\b|^Caused by:|^[[:space:]]+'
      negate: false
      match: after
    processors:
    - decode_json_fields:
        fields: ["message"]
    - add_locale: {}
  daemonSet:
    podTemplate:
      spec:
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: false
        securityContext:
          runAsUser: 0
        containers:
        - name: filebeat
          args:
            - --log-verbosity=1
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          resources:
            requests:
              memory: 512Mi
              cpu: 0.5
            limits:
              memory: 2.5Gi
              cpu: 2
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
